# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from collections.abc import Iterator
from uuid import uuid4

import pytest

import framework.fixtures  # noqa: F401
from e2efast.fixture_registry import get_fixtures

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import (
    TokenObtainPairWithProperMessage,
    UserRegister,
)

"""
    Need for auto registration fixtures, you can append more fixtures to this list.

    Example:
        pytest_plugins = get_fixtures()
        pytest_plugins += ["fixture1", "fixture2"]
"""  # noqa: E501

pytest_plugins = get_fixtures()


@pytest.fixture
def with_auth(book_club_service: BookClubService) -> Iterator[None]:
    uid = str(uuid4())
    book_club_service.users.post_api_v1_users_register_with_http_info(
        UserRegister(username=uid, password="TestPass123!"),
    )
    raw = book_club_service.auth.post_api_v1_auth_token_with_http_info(
        TokenObtainPairWithProperMessage(username=uid, password="TestPass123!"),
    )
    tokens = raw.json()
    book_club_service.api_client.headers["Authorization"] = f"Bearer {tokens['access']}"

    yield

    book_club_service.users.delete_api_v1_users_me_with_http_info()
    book_club_service.api_client.headers.pop("Authorization", None)
