# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1
"""  # noqa: E501

from uuid import uuid4

import httpx
import pytest

import framework.fixtures  # noqa: F401
from e2efast.fixture_registry import get_fixtures

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import (
    TokenObtainPairWithProperMessage,
    UserRegister,
)

"""
    Need for auto registration fixtures, you can append more fixtures to this list.

    Example:
        pytest_plugins = get_fixtures()
        pytest_plugins += ["fixture1", "fixture2"]
"""  # noqa: E501

pytest_plugins = get_fixtures()


@pytest.fixture
def test_credentials(book_club_service: BookClubService):
    uid = str(uuid4())
    book_club_service.users.post_api_v1_users_register_with_http_info(
        UserRegister(username=uid, password="TestPass123!"),
    )
    resp = book_club_service.auth.post_api_v1_auth_token_with_http_info(
        TokenObtainPairWithProperMessage(username=uid, password="TestPass123!"),
    )
    tokens = resp.json()
    yield {
        "username": uid,
        "password": "TestPass123!",
        "access": tokens["access"],
        "refresh": tokens["refresh"],
    }
    book_club_service.users.delete_api_v1_users_me()


@pytest.fixture
def with_auth(book_club_service_client: httpx.Client, test_credentials: dict) -> None:
    book_club_service_client.headers["Authorization"] = (
        f"Bearer {test_credentials['access']}"
    )
