version: '3'

tasks:
  default:
    cmds:
      - task: help

  install-deps:
    cmds:
      - poetry install

  fmt:
    cmds:
      - poetry run ruff check . --fix --unsafe-fixes
      - poetry run ruff format

  lint:
    cmds:
      - poetry run ruff check .

  test:
    cmds:
      - poetry run pytest src/tests --dead-fixtures
      - poetry run pytest src/tests --exitfirst --alluredir=allure-results --cov --cov-report=xml:cov.xml --cov-report=term-missing:skip-covered


  run:
    dir: src
    cmds:
      - poetry run uvicorn main:app --port 8000


  help:
    cmds:
      - |
        echo "Taskfile for api coverage by swagger tool"
        echo ""
        echo "Usage:"
        echo "  task install-deps       Install dependencies"
        echo "  task fmt                Format code"
        echo "  task lint               Lint code"
        echo "  task test               Run tests"
        echo "  task help               Show this help message"
        echo "  task run                Run app"