# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService


@pytest.mark.skip
def test_get_api_v1_clubs(book_club_service: BookClubService):

    membership = ...
    page = ...
    page_size = ...
    search = ...

    response = book_club_service.clubs.get_api_v1_clubs(
        membership=membership, page=page, page_size=page_size, search=search
    )
    assert response is not None
