# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from datetime import datetime, timezone
from uuid import uuid4

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import Club


def test_get_api_v1_clubs_id(
    book_club_service: BookClubService, with_auth: None
) -> None:
    now = datetime.now(timezone.utc)
    book_title = f"Книга {uuid4()}"
    created = book_club_service.clubs.post_api_v1_clubs_with_http_info(
        Club(
            id=0,
            bookTitle=book_title,
            bookAuthors="Автор",
            publicationYear=2024,
            description="Описание",
            telegramChatLink="https://t.me/testclub",
            owner=0,
            members=[],
            reviews=[],
            created=now,
            modified=now,
        ),
    )
    response = book_club_service.clubs.get_api_v1_clubs_id_with_http_info(
        id_=created.json()["id"]
    )
    assert response.json()["id"] == created.json()["id"]
    assert response.json()["bookTitle"]
