# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from datetime import datetime, timezone
from uuid import uuid4

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import Club


def test_put_api_v1_clubs_id(
    book_club_service: BookClubService, with_auth: None
) -> None:
    now = datetime.now(timezone.utc)
    original_title = f"Книга {uuid4()}"
    updated_title = f"Книга {uuid4()}"
    created = book_club_service.clubs.post_api_v1_clubs_with_http_info(
        Club(
            id=0,
            bookTitle=original_title,
            bookAuthors="Автор",
            publicationYear=2024,
            description="Описание",
            telegramChatLink="https://t.me/testclub",
            owner=0,
            members=[],
            reviews=[],
            created=now,
            modified=now,
        ),
    )
    response = book_club_service.clubs.put_api_v1_clubs_id_with_http_info(
        Club(
            id=created.json()["id"],
            bookTitle=updated_title,
            bookAuthors="Новый автор",
            publicationYear=2025,
            description="Новое описание",
            telegramChatLink="https://t.me/updated",
            owner=created.json()["owner"],
            members=created.json()["members"],
            reviews=created.json()["reviews"],
            created=created.json()["created"],
            modified=datetime.now(timezone.utc),
        ),
        id_=created.json()["id"],
    )
    assert response.json()["bookTitle"] == updated_title
    assert response.json()["bookAuthors"] == "Новый автор"
