# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService


@pytest.mark.skip
def test_delete_api_v1_clubs_id(book_club_service: BookClubService):

    id_ = ...

    response = book_club_service.clubs.delete_api_v1_clubs_id(id_=id_)
    assert response is not None
