# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from datetime import datetime, timezone
from uuid import uuid4

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import (
    Club,
    TokenObtainPairWithProperMessage,
    UserRegister,
)


def test_post_api_v1_clubs_id__members_me(
    book_club_service: BookClubService, with_auth: None
) -> None:
    now = datetime.now(timezone.utc)
    book_title = f"Клуб {uuid4()}"
    created = book_club_service.clubs.post_api_v1_clubs_with_http_info(
        Club(
            id=0,
            bookTitle=book_title,
            bookAuthors="Автор",
            publicationYear=2024,
            description="Вступить в клуб",
            telegramChatLink="https://t.me/testclub",
            owner=0,
            members=[],
            reviews=[],
            created=now,
            modified=now,
        ),
    )
    club_id = created.json()["id"]

    uid2 = str(uuid4())
    book_club_service.users.post_api_v1_users_register_with_http_info(
        UserRegister(username=uid2, password="TestPass123!"),
    )
    raw2 = book_club_service.auth.post_api_v1_auth_token_with_http_info(
        TokenObtainPairWithProperMessage(username=uid2, password="TestPass123!"),
    )
    token2 = raw2.json()["access"]

    book_club_service.api_client.headers["Authorization"] = f"Bearer {token2}"
    response = book_club_service.clubs.post_api_v1_clubs_id__members_me_with_http_info(
        id_=club_id,
    )
    assert response.status_code in (200, 201, 204)
