# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from datetime import datetime, timezone
from uuid import uuid4

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import (
    BookReview,
    Club,
    User,
)


def test_put_api_v1_clubs_reviews_id(
    book_club_service: BookClubService, with_auth: None
) -> None:
    now = datetime.now(timezone.utc)
    book_title = f"Книга {uuid4()}"
    club = book_club_service.clubs.post_api_v1_clubs_with_http_info(
        Club(
            id=0,
            bookTitle=book_title,
            bookAuthors="Автор",
            publicationYear=2024,
            description="Описание",
            telegramChatLink="https://t.me/testclub",
            owner=0,
            members=[],
            reviews=[],
            created=now,
            modified=now,
        ),
    )
    review = book_club_service.clubs.post_api_v1_clubs_reviews_with_http_info(
        BookReview(
            id=0,
            club=club.json()["id"],
            user=User(id=0, username="test"),
            review="Оригинальный отзыв",
            assessment=3,
            readPages=150,
            created=now,
            modified=now,
        ),
    )
    response = book_club_service.clubs.put_api_v1_clubs_reviews_id_with_http_info(
        BookReview(
            id=review.json()["id"],
            club=review.json()["club"],
            user=review.json()["user"],
            review="Обновлённый отзыв",
            assessment=5,
            readPages=300,
            created=review.json()["created"],
            modified=datetime.now(timezone.utc),
        ),
        id_=review.json()["id"],
    )
    assert response.json()["review"] == "Обновлённый отзыв"
    assert response.json()["assessment"] == 5
