# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from framework.fixtures.http.book_club_service import BookClubService


def test_get_api_v1_clubs(book_club_service: BookClubService, with_auth: None) -> None:
    response = book_club_service.clubs.get_api_v1_clubs_with_http_info()
    assert response.json()["count"] >= 0
    assert isinstance(response.json()["results"], list)
