# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import PatchedClub


@pytest.mark.skip
def test_patch_api_v1_clubs_id(book_club_service: BookClubService):
    patched_club = PatchedClub()

    id_ = ...

    response = book_club_service.clubs.patch_api_v1_clubs_id(
        patched_club=patched_club, id_=id_
    )
    assert response is not None
