"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: book_club
    version: 2.0.1

    Do not edit the class manually.
"""  # noqa: E501

from internal.clients.http.book_club.apis.users_api import UsersApi
from internal.clients.http.book_club.apis.docs_api import DocsApi
from internal.clients.http.book_club.apis.clubs_api import ClubsApi
from internal.clients.http.book_club.apis.auth_api import AuthApi

__all__ = [
    "UsersApi",
    "DocsApi",
    "ClubsApi",
    "AuthApi",
]
