# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from uuid import uuid4

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import UserRegister


def test_post_api_v1_users_register(book_club_service: BookClubService) -> None:
    uid = str(uuid4())
    raw = book_club_service.users.post_api_v1_users_register_with_http_info(
        UserRegister(username=uid, password="TestPass123!"),
    )
    assert raw.status_code == 201
