# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import PatchedUser


@pytest.mark.skip
def test_patch_api_v1_users_me(book_club_service: BookClubService):
    patched_user = PatchedUser()

    response = book_club_service.users.patch_api_v1_users_me(patched_user=patched_user)
    assert response is not None
