# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import UserRegister


@pytest.mark.skip
def test_post_api_v1_users_register(book_club_service: BookClubService):
    user_register = UserRegister()

    response = book_club_service.users.post_api_v1_users_register(
        user_register=user_register
    )
    assert response is not None
