# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from framework.fixtures.http.book_club_service import BookClubService


def test_get_api_v1_users_me(
    book_club_service: BookClubService, _auth_setup: None
) -> None:
    user = book_club_service.users.get_api_v1_users_me()
    assert user.id > 0
    assert user.username
