# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from framework.fixtures.http.book_club_service import BookClubService


def test_get_api_v1_docs_schema(
    book_club_service: BookClubService, with_auth: None
) -> None:
    response = book_club_service.docs.get_api_v1_docs_schema(format_="json")
    assert isinstance(response.root, dict)
    assert "paths" in response.root
    assert "info" in response.root
