# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService


@pytest.mark.skip
def test_get_api_v1_docs_schema(book_club_service: BookClubService):

    format_ = ...
    lang = ...

    response = book_club_service.docs.get_api_v1_docs_schema(format_=format_, lang=lang)
    assert response is not None
