# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from internal.clients.http.book_club.models import *  # noqa: F401, F403
from internal.clients.http.book_club.apis.docs_api import DocsApi


class DocsClient(DocsApi):
    """
    You can edit this class manually.

    For override methods see DocsApi.
    """
