# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: book_club
    version: 2.0.1

    Do not edit the class manually.
"""  # noqa: E501

from httpx import Response
from typing import Any

from httpx import Client


from internal.clients.http.book_club.models.api_models import (
    TokenRefresh,
    TokenBlacklist,
    TokenObtainPairWithProperMessage,
)


class AuthApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def post_api_v1_auth_logout(
        self,
        token_blacklist: TokenBlacklist,  # noqa: E501
        **kwargs: Any,
    ) -> TokenBlacklist:
        """
        No summary description.

        Args:
            token_blacklist(TokenBlacklist): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            TokenBlacklist: ...
        """  # noqa: D205,E501

        response = self.post_api_v1_auth_logout_with_http_info(
            token_blacklist=token_blacklist,  # noqa: E501
            **kwargs,
        )
        return TokenBlacklist.model_validate_json(response.text)

    def post_api_v1_auth_logout_with_http_info(
        self,
        token_blacklist: TokenBlacklist,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            token_blacklist(TokenBlacklist): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = token_blacklist.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/api/v1/auth/logout/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_auth_token(
        self,
        token_obtain_pair_with_proper_message: TokenObtainPairWithProperMessage,  # noqa: E501
        **kwargs: Any,
    ) -> TokenObtainPairWithProperMessage:
        """
        No summary description.

        Args:
            token_obtain_pair_with_proper_message(TokenObtainPairWithProperMessage): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            TokenObtainPairWithProperMessage: ...
        """  # noqa: D205,E501

        response = self.post_api_v1_auth_token_with_http_info(
            token_obtain_pair_with_proper_message=token_obtain_pair_with_proper_message,  # noqa: E501
            **kwargs,
        )
        return TokenObtainPairWithProperMessage.model_validate_json(response.text)

    def post_api_v1_auth_token_with_http_info(
        self,
        token_obtain_pair_with_proper_message: TokenObtainPairWithProperMessage,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            token_obtain_pair_with_proper_message(TokenObtainPairWithProperMessage): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = token_obtain_pair_with_proper_message.model_dump_json(
            exclude_none=True, by_alias=True
        )  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/api/v1/auth/token/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_auth_token_refresh(
        self,
        token_refresh: TokenRefresh,  # noqa: E501
        **kwargs: Any,
    ) -> TokenRefresh:
        """
        No summary description.

        Args:
            token_refresh(TokenRefresh): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            TokenRefresh: ...
        """  # noqa: D205,E501

        response = self.post_api_v1_auth_token_refresh_with_http_info(
            token_refresh=token_refresh,  # noqa: E501
            **kwargs,
        )
        return TokenRefresh.model_validate_json(response.text)

    def post_api_v1_auth_token_refresh_with_http_info(
        self,
        token_refresh: TokenRefresh,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            token_refresh(TokenRefresh): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = token_refresh.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/api/v1/auth/token/refresh/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response
