# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: book_club
    version: 2.0.1

    Do not edit the class manually.
"""  # noqa: E501

from httpx import Response
from typing import Any

from httpx import Client


from internal.clients.http.book_club.models.api_models import (
    PatchedBookReview,
    PatchedClub,
    PaginatedClubList,
    BookReview,
    Club,
    PaginatedBookReviewList,
)


class ClubsApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_api_v1_clubs(
        self,
        membership: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
        search: str | None = None,
        **kwargs: Any,
    ) -> PaginatedClubList:
        """
        No summary description.

        Args:
            membership(str | None, optional): ...
            page(int | None, optional): A page number within the paginated result set.
            page_size(int | None, optional): Number of results to return per page.
            search(str | None, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            PaginatedClubList: ...
        """  # noqa: D205,E501

        response = self.get_api_v1_clubs_with_http_info(
            membership=membership,
            page=page,
            page_size=page_size,
            search=search,
            **kwargs,
        )
        return PaginatedClubList.model_validate_json(response.text)

    def get_api_v1_clubs_with_http_info(
        self,
        membership: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
        search: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            membership(str, optional): ...
            page(int, optional): A page number within the paginated result set.
            page_size(int, optional): Number of results to return per page.
            search(str, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        # process the query parameters
        params_map = {
            "membership": membership,
            "page": page,
            "page_size": page_size,
            "search": search,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url=f"/api/v1/clubs/",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_clubs(
        self,
        club: Club,  # noqa: E501
        **kwargs: Any,
    ) -> Club:
        """
        No summary description.

        Args:
            club(Club): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Club: ...
        """  # noqa: D205,E501

        response = self.post_api_v1_clubs_with_http_info(
            club=club,  # noqa: E501
            **kwargs,
        )
        return Club.model_validate_json(response.text)

    def post_api_v1_clubs_with_http_info(
        self,
        club: Club,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            club(Club): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = club.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/api/v1/clubs/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def get_api_v1_clubs_id(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Club:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Club: ...
        """  # noqa: D205,E501

        response = self.get_api_v1_clubs_id_with_http_info(
            id_=id_,
            **kwargs,
        )
        return Club.model_validate_json(response.text)

    def get_api_v1_clubs_id_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url=f"/api/v1/clubs/{id_}/",
            headers=headers,
            **kwargs,
        )
        return response

    def put_api_v1_clubs_id(
        self,
        club: Club,  # noqa: E501
        id_: int,
        **kwargs: Any,
    ) -> Club:
        """
        No summary description.

        Args:
            club(Club): ...
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Club: ...
        """  # noqa: D205,E501

        response = self.put_api_v1_clubs_id_with_http_info(
            id_=id_,
            club=club,  # noqa: E501
            **kwargs,
        )
        return Club.model_validate_json(response.text)

    def put_api_v1_clubs_id_with_http_info(
        self,
        club: Club,  # noqa: E501
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            club(Club): ...
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = club.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.put(
            url=f"/api/v1/clubs/{id_}/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def patch_api_v1_clubs_id(
        self,
        patched_club: PatchedClub,  # noqa: E501
        id_: int,
        **kwargs: Any,
    ) -> Club:
        """
        No summary description.

        Args:
            patched_club(PatchedClub): ...
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Club: ...
        """  # noqa: D205,E501

        response = self.patch_api_v1_clubs_id_with_http_info(
            id_=id_,
            patched_club=patched_club,  # noqa: E501
            **kwargs,
        )
        return Club.model_validate_json(response.text)

    def patch_api_v1_clubs_id_with_http_info(
        self,
        patched_club: PatchedClub,  # noqa: E501
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            patched_club(PatchedClub): ...
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = patched_club.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.patch(
            url=f"/api/v1/clubs/{id_}/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_id(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response = self.delete_api_v1_clubs_id_with_http_info(
            id_=id_,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_id_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url=f"/api/v1/clubs/{id_}/",
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_clubs_id__members_me(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response = self.post_api_v1_clubs_id__members_me_with_http_info(
            id_=id_,
            **kwargs,
        )
        return response

    def post_api_v1_clubs_id__members_me_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.post(
            url=f"/api/v1/clubs/{id_}/members/me/",
            headers=headers,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_id__members_me(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response = self.delete_api_v1_clubs_id__members_me_with_http_info(
            id_=id_,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_id__members_me_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            id_(int, required): A unique integer value identifying this Book Club.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url=f"/api/v1/clubs/{id_}/members/me/",
            headers=headers,
            **kwargs,
        )
        return response

    def get_api_v1_clubs_reviews(
        self,
        club: int | None = None,
        page: int | None = None,
        page_size: int | None = None,
        **kwargs: Any,
    ) -> PaginatedBookReviewList:
        """
        No summary description.

        Args:
            club(int | None, optional): ...
            page(int | None, optional): A page number within the paginated result set.
            page_size(int | None, optional): Number of results to return per page.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            PaginatedBookReviewList: ...
        """  # noqa: D205,E501

        response = self.get_api_v1_clubs_reviews_with_http_info(
            club=club,
            page=page,
            page_size=page_size,
            **kwargs,
        )
        return PaginatedBookReviewList.model_validate_json(response.text)

    def get_api_v1_clubs_reviews_with_http_info(
        self,
        club: int | None = None,
        page: int | None = None,
        page_size: int | None = None,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            club(int, optional): ...
            page(int, optional): A page number within the paginated result set.
            page_size(int, optional): Number of results to return per page.
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        # process the query parameters
        params_map = {
            "club": club,
            "page": page,
            "page_size": page_size,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url=f"/api/v1/clubs/reviews/",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_clubs_reviews(
        self,
        book_review: BookReview,  # noqa: E501
        **kwargs: Any,
    ) -> BookReview:
        """
        No summary description.

        Args:
            book_review(BookReview): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            BookReview: ...
        """  # noqa: D205,E501

        response = self.post_api_v1_clubs_reviews_with_http_info(
            book_review=book_review,  # noqa: E501
            **kwargs,
        )
        return BookReview.model_validate_json(response.text)

    def post_api_v1_clubs_reviews_with_http_info(
        self,
        book_review: BookReview,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            book_review(BookReview): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = book_review.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/api/v1/clubs/reviews/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def get_api_v1_clubs_reviews_id(
        self,
        id_: int,
        **kwargs: Any,
    ) -> BookReview:
        """
                No summary description.

                Args:
                    id_(int, required): A unique integer value identifying this Book
        Review.
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    BookReview: ...
        """  # noqa: D205,E501

        response = self.get_api_v1_clubs_reviews_id_with_http_info(
            id_=id_,
            **kwargs,
        )
        return BookReview.model_validate_json(response.text)

    def get_api_v1_clubs_reviews_id_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    id_(int, required): A unique integer value identifying this Book
        Review.
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url=f"/api/v1/clubs/reviews/{id_}/",
            headers=headers,
            **kwargs,
        )
        return response

    def put_api_v1_clubs_reviews_id(
        self,
        book_review: BookReview,  # noqa: E501
        id_: int,
        **kwargs: Any,
    ) -> BookReview:
        """
                No summary description.

                Args:
                    book_review(BookReview): ...
                    id_(int, required): A unique integer value identifying this Book
        Review.
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    BookReview: ...
        """  # noqa: D205,E501

        response = self.put_api_v1_clubs_reviews_id_with_http_info(
            id_=id_,
            book_review=book_review,  # noqa: E501
            **kwargs,
        )
        return BookReview.model_validate_json(response.text)

    def put_api_v1_clubs_reviews_id_with_http_info(
        self,
        book_review: BookReview,  # noqa: E501
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    book_review(BookReview): ...
                    id_(int, required): A unique integer value identifying this Book
        Review.
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = book_review.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.put(
            url=f"/api/v1/clubs/reviews/{id_}/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def patch_api_v1_clubs_reviews_id(
        self,
        patched_book_review: PatchedBookReview,  # noqa: E501
        id_: int,
        **kwargs: Any,
    ) -> BookReview:
        """
                No summary description.

                Args:
                    patched_book_review(PatchedBookReview): ...
                    id_(int, required): A unique integer value identifying this Book
        Review.
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    BookReview: ...
        """  # noqa: D205,E501

        response = self.patch_api_v1_clubs_reviews_id_with_http_info(
            id_=id_,
            patched_book_review=patched_book_review,  # noqa: E501
            **kwargs,
        )
        return BookReview.model_validate_json(response.text)

    def patch_api_v1_clubs_reviews_id_with_http_info(
        self,
        patched_book_review: PatchedBookReview,  # noqa: E501
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    patched_book_review(PatchedBookReview): ...
                    id_(int, required): A unique integer value identifying this Book
        Review.
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = patched_book_review.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.patch(
            url=f"/api/v1/clubs/reviews/{id_}/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_reviews_id(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    id_(int, required): A unique integer value identifying this Book
        Review.
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.delete_api_v1_clubs_reviews_id_with_http_info(
            id_=id_,
            **kwargs,
        )
        return response

    def delete_api_v1_clubs_reviews_id_with_http_info(
        self,
        id_: int,
        **kwargs: Any,
    ) -> Response:
        """
                No summary description.

                Args:
                    id_(int, required): A unique integer value identifying this Book
        Review.
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url=f"/api/v1/clubs/reviews/{id_}/",
            headers=headers,
            **kwargs,
        )
        return response
