# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: book_club
    version: 2.0.1

    Do not edit the class manually.
"""  # noqa: E501

from httpx import Response
from typing import Any

from httpx import Client


from internal.clients.http.book_club.models.api_models import (
    PatchedUser,
    UserRegister,
    User,
)


class UsersApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_api_v1_users_me(
        self,
        **kwargs: Any,
    ) -> User:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            User: ...
        """  # noqa: D205,E501

        response = self.get_api_v1_users_me_with_http_info(
            **kwargs,
        )
        return User.model_validate_json(response.text)

    def get_api_v1_users_me_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url=f"/api/v1/users/me/",
            headers=headers,
            **kwargs,
        )
        return response

    def put_api_v1_users_me(
        self,
        user: User,  # noqa: E501
        **kwargs: Any,
    ) -> User:
        """
        No summary description.

        Args:
            user(User): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            User: ...
        """  # noqa: D205,E501

        response = self.put_api_v1_users_me_with_http_info(
            user=user,  # noqa: E501
            **kwargs,
        )
        return User.model_validate_json(response.text)

    def put_api_v1_users_me_with_http_info(
        self,
        user: User,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            user(User): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = user.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.put(
            url=f"/api/v1/users/me/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def patch_api_v1_users_me(
        self,
        patched_user: PatchedUser,  # noqa: E501
        **kwargs: Any,
    ) -> User:
        """
        No summary description.

        Args:
            patched_user(PatchedUser): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            User: ...
        """  # noqa: D205,E501

        response = self.patch_api_v1_users_me_with_http_info(
            patched_user=patched_user,  # noqa: E501
            **kwargs,
        )
        return User.model_validate_json(response.text)

    def patch_api_v1_users_me_with_http_info(
        self,
        patched_user: PatchedUser,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            patched_user(PatchedUser): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = patched_user.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.patch(
            url=f"/api/v1/users/me/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_api_v1_users_me(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response = self.delete_api_v1_users_me_with_http_info(
            **kwargs,
        )
        return response

    def delete_api_v1_users_me_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url=f"/api/v1/users/me/",
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_v1_users_register(
        self,
        user_register: UserRegister,  # noqa: E501
        **kwargs: Any,
    ) -> UserRegister:
        """
        No summary description.

        Args:
            user_register(UserRegister): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            UserRegister: ...
        """  # noqa: D205,E501

        response = self.post_api_v1_users_register_with_http_info(
            user_register=user_register,  # noqa: E501
            **kwargs,
        )
        return UserRegister.model_validate_json(response.text)

    def post_api_v1_users_register_with_http_info(
        self,
        user_register: UserRegister,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        No summary description.

        Args:
            user_register(UserRegister): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = user_register.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url=f"/api/v1/users/register/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response
