# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import TokenRefresh


@pytest.mark.skip
def test_post_api_v1_auth_token_refresh(book_club_service: BookClubService):
    token_refresh = TokenRefresh()

    response = book_club_service.auth.post_api_v1_auth_token_refresh(
        token_refresh=token_refresh
    )
    assert response is not None
