# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import TokenBlacklist


@pytest.mark.skip
def test_post_api_v1_auth_logout(book_club_service: BookClubService):
    token_blacklist = TokenBlacklist()

    response = book_club_service.auth.post_api_v1_auth_logout(
        token_blacklist=token_blacklist
    )
    assert response is not None
