# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

import pytest

from framework.fixtures.http.book_club_service import BookClubService
from internal.clients.http.book_club.models.api_models import (
    TokenObtainPairWithProperMessage,
)


@pytest.mark.skip
def test_post_api_v1_auth_token(book_club_service: BookClubService):
    token_obtain_pair_with_proper_message = TokenObtainPairWithProperMessage()

    response = book_club_service.auth.post_api_v1_auth_token(
        token_obtain_pair_with_proper_message=token_obtain_pair_with_proper_message
    )
    assert response is not None
