"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: {{ service_name|to_snake_case }}
    version: {{ version }}

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field, RootModel


class PatchedUser(BaseModel):
    id: int | None = None
    username: str | None = Field(
        None,
        description="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        max_length=150,
        pattern="^[\\w.@+-]+$",
    )
    first_name: str | None = Field(None, alias="firstName", max_length=150)
    last_name: str | None = Field(None, alias="lastName", max_length=150)
    email: EmailStr | None = Field(None, max_length=254, title="Email address")
    remote_addr: str | None = Field(None, alias="remoteAddr")


class TokenBlacklist(BaseModel):
    refresh: str


class TokenObtainPairWithProperMessage(BaseModel):
    username: str
    password: str


class TokenRefresh(BaseModel):
    access: str
    refresh: str


class User(BaseModel):
    id: int
    username: str = Field(
        ...,
        description="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        max_length=150,
        pattern="^[\\w.@+-]+$",
    )


class UserRegister(BaseModel):
    username: str = Field(
        ...,
        description="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        max_length=150,
        pattern="^[\\w.@+-]+$",
    )
    password: str = Field(..., max_length=128)


class DocsSchemaRetrieveResponse200(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class BookReview(BaseModel):
    id: int
    club: int
    user: User
    review: str = Field(..., title="Book Review")
    assessment: int = Field(..., ge=1, le=5)
    read_pages: int = Field(..., alias="readPages", ge=-2147483648, le=2147483647)
    created: AwareDatetime = Field(..., title="Дата создания")
    modified: AwareDatetime = Field(..., title="Дата изменения")


class Club(BaseModel):
    id: int
    book_title: str = Field(..., alias="bookTitle", max_length=255)
    book_authors: str = Field(..., alias="bookAuthors", max_length=255)
    publication_year: int = Field(
        ..., alias="publicationYear", ge=-2147483648, le=2147483647
    )
    description: str = Field(..., title="Book Description")
    telegram_chat_link: AnyUrl = Field(
        ..., alias="telegramChatLink", title="Link on Telegram chat"
    )
    owner: int
    members: list[int]
    reviews: list[BookReview]
    created: AwareDatetime = Field(..., title="Дата создания")
    modified: AwareDatetime = Field(..., title="Дата изменения")


class PaginatedBookReviewList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?page=4"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?page=2"]
    )
    results: list[BookReview]


class PaginatedClubList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?page=4"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?page=2"]
    )
    results: list[Club]


class PatchedBookReview(BaseModel):
    id: int | None = None
    club: int | None = None
    user: User | None = None
    review: str | None = Field(None, title="Book Review")
    assessment: int | None = Field(None, ge=1, le=5)
    read_pages: int | None = Field(
        None, alias="readPages", ge=-2147483648, le=2147483647
    )
    created: AwareDatetime | None = Field(None, title="Дата создания")
    modified: AwareDatetime | None = Field(None, title="Дата изменения")


class PatchedClub(BaseModel):
    id: int | None = None
    book_title: str | None = Field(None, alias="bookTitle", max_length=255)
    book_authors: str | None = Field(None, alias="bookAuthors", max_length=255)
    publication_year: int | None = Field(
        None, alias="publicationYear", ge=-2147483648, le=2147483647
    )
    description: str | None = Field(None, title="Book Description")
    telegram_chat_link: AnyUrl | None = Field(
        None, alias="telegramChatLink", title="Link on Telegram chat"
    )
    owner: int | None = None
    members: list[int] | None = None
    reviews: list[BookReview] | None = None
    created: AwareDatetime | None = Field(None, title="Дата создания")
    modified: AwareDatetime | None = Field(None, title="Дата изменения")
