# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: fixtures.base
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from functools import partial

from framework.clients.http.base_client import Client, Configuration

"""
You can redefine client class for own needs, client should be a subclass of httpx.Client

Example:
    from httpx import AsyncClient
    ClientClass = AsyncClient

You can add default timeout or other parameters to client class with functools.partial

Example:
    from httpx import Timeout
    ClientClass = partial(httpx.Client, timeout=Timeout(60.0))

"""
ClientClass = partial(
    Client,
    configuration=Configuration(),
)
