# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    Do not edit the class manually.
"""  # noqa: E501

from typing import TypeVar

import httpx

import pytest


from framework.clients.http.book_club.auth_client import AuthClient
from framework.clients.http.book_club.clubs_client import ClubsClient
from framework.clients.http.book_club.docs_client import DocsClient
from framework.clients.http.book_club.users_client import UsersClient

from framework.fixtures.http.base import ClientClass
from framework.settings.base_settings import Settings
from e2efast.fixture_registry import register_fixture

ClientType = TypeVar("ClientType", bound=httpx.Client)


class BookClubService:
    def __init__(self, api_client: ClientType) -> None:
        self.api_client = api_client
        self.auth = AuthClient(api_client=api_client)
        self.clubs = ClubsClient(api_client=api_client)
        self.docs = DocsClient(api_client=api_client)
        self.users = UsersClient(api_client=api_client)


@pytest.fixture(scope="session")
def book_club_service_client() -> ClientType:
    client = ClientClass()
    client.base_url = Settings().book_club
    return client


@pytest.fixture(scope="session")
def book_club_service(book_club_service_client: ClientType) -> BookClubService:
    return BookClubService(api_client=book_club_service_client)


register_fixture(__name__)
