# coding: utf-8
"""
Generated by e2efast (https://github.com/ValeriyMenshikov/e2efast).

    source: book_club
    version: 1.0.1

    You can manually edit this file.
"""  # noqa: E501

from pydantic_settings import BaseSettings
from pydantic import Field


class Settings(BaseSettings):
    """Environment-driven configuration for HTTP clients."""

    book_club: str | None = Field(
        default="http://127.0.0.1:8000/proxy",
        alias="BOOK_CLUB_BASE_URL",
        description="Base URL for the service",
    )


__all__ = ["Settings"]
